/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;

/**
 *
 * @author Muzaffar
 */
public class NewApplication extends javax.swing.JFrame {

    private double alfa;
    private double alfa1;
    private double a;
    private double B;
    private double b0;
    private double l_sh;
    private double h_bl;
    private double dH;
    private double H;

    private Graphics2D g;

    private Line2D lineBuffer;
    private Ellipse2D circBuffer;

    private List<Line2D> lineContainer = new ArrayList();
    private List<Ellipse2D> circContainer = new ArrayList();

    static double x0 = 400, y0 = 100; // нулевая точка
    static int z1 = 9, z3 = 9;

    /**
     * Creates new form NewApplication
     */
    public NewApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextB = new javax.swing.JTextField();
        jTextH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTexth_bl = new javax.swing.JTextField();
        jTextl_sh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ширина осн. площадки, B");

        jLabel2.setText("Высота насыпи, H");

        jTextB.setText("7.6");

        jTextH.setText("4");

        jLabel3.setText("Толщина балласта, hб");

        jLabel4.setText("Длина шпалы, lш");

        jTexth_bl.setText("0.5");

        jTextl_sh.setText("2.7");

        jLabel5.setText("1:m уклон откоса");

        jTextm.setText("1");

        jButton1.setText("Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jButton2.setText("Clear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53)
                                .addComponent(jTextm, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextH, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(jTextB)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTexth_bl)
                                    .addComponent(jTextl_sh, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(613, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexth_bl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextl_sh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        B = Float.parseFloat(jTextB.getText());
        H = Float.parseFloat(jTextH.getText());
        h_bl = Float.parseFloat(jTexth_bl.getText());
        l_sh = Float.parseFloat(jTextl_sh.getText());

//        alfa1 = Math.toDegrees(Math.atan(1 / Float.parseFloat(jTextm.getText())));
        alfa1 = Math.atan(1 / Float.parseFloat(jTextm.getText())); //получаем в радианах

        b0 = (l_sh + 2 * h_bl * Math.tan(Math.toRadians(30)));
        dH = (0.1 * b0);
        a = (B - b0) / 2;

        alfa = Math.toDegrees(Math.atan(H / (a + H * 1 / Math.tan(alfa1))));
//        alfa = Math.toDegrees(Math.atan(1));

        double alfaG = Math.toRadians(alfa);

//        System.out.println("b0 = " + b0 + "; dH = " + dH + "; a = " + a + "; alfa1 = " + alfa1 + "; alfa = " + alfa + "; alfaG = " + alfaG);
//        System.out.println("1 / Math.tan(Math.toRadians(alfa1) " + 1 / Math.tan(Math.toRadians(alfa1)));
//        System.out.println("Math.atan(Math.toRadians(45)) -->> "+Math.tan(Math.toRadians(30)));
//        System.out.println("Math.toRadians(45) -->> "+Math.toRadians(30));
//        System.out.println("Math.atan(Math.tan(Math.toRadians(30))) -->> "+Math.toDegrees(Math.atan(Math.tan(Math.toRadians(30)))));
//
//        double grad = Math.tan(Math.toRadians(45));
//        double grad = Math.tan(alfa);
//        System.out.println("grad " + (float) grad);
//        double agrad = Math.atan(grad);
//        System.out.println("agrad " + (float) agrad);
//        double I = Math.toDegrees(agrad);
//        int i = (int) I;
//        System.out.println("i --> " + i);
//        double J = ((I - i) * 60);
//        int j = (int) J;
//        System.out.println("j ---> " + j);
//        double K = (J - j) * 60;
//        int k = (int) K;
//        System.out.println("k ---> " + k);
        //
        //Начинаем построить график
        //
        g = (Graphics2D) jPanel2.getGraphics();
//        double x0 = 400, y0 = 100; // нулевая точка
//
//        g.drawLine((int) x0, (int) y0, (int) (x0 + b0 * 100), (int) y0);
//        for (int l = 0; l < 10; l++) {
//            double x1 = (x0 + Math.cos(Math.toRadians(0)) * (100 * dH));
//            double y1 = (y0 + Math.sin(Math.toRadians(0)) * (100 * dH));
//            lineBuffer = new Line2D.Double(x0, y0, x1, y1);
//            lineContainer.add(lineBuffer);
//
//            x0 = x1;
//            y0 = y1;
//            System.out.println(x0 + " - " + y0);
//            DrawAll();
//        }
//        DrawLineHor(x0, y0);

//        for (int qq = 0; qq < 10; qq++) {
//
//            double x1 = (x0 + Math.cos(Math.toRadians(180 - alfa)) * (100 * dH));
//            double y1 = (y0 + Math.sin(Math.toRadians(180 - alfa)) * (100 * dH));
//
//            lineBuffer = new Line2D.Double(x0, y0, x1, y1);
//            lineContainer.add(lineBuffer);
//
//            x0 = x1;
//            y0 = y1;
//
//            circBuffer = new Ellipse2D.Double((x0 - 3), (y0 - 3), 6, 6);
//            circContainer.add(circBuffer);
//
//            DrawAll();
//        }
//        System.out.println(x0 + " - " + y0);
        for (int l = 0; l < 3; l++) {

            DrawLineVert(x0, y0, alfa);

            if (l == 1) {

                for (int m = 0; m < 10; m++) {

                    DrawLineVert(lineContainer.get(m).getX2(), lineContainer.get(m).getY2(), alfa);
                    z1--;

                }
            } 
//            else if (l == 2) {
//
//                System.out.println("lineContainer.size() " + lineContainer.size());
//                for (int m = 10; m > 0; m--) {
////                    System.out.println("z3-- " + z3);
//                    DrawLineVert(lineContainer.get(m).getX2(), lineContainer.get(m).getY2(), alfa);
//                    z3--;
//                }
//            }
            alfa += 45;
        }

        DrawLineHor(x0, y0);

        DrawAll();

        System.out.println("list " + lineContainer.size());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        z1 = 9;
        z3 = 9;
        jPanel2.update(g);
        lineContainer.clear();
        circContainer.clear();
    }//GEN-LAST:event_jButton2MouseClicked

    private void DrawAll() {
        for (int i = 0; i < lineContainer.size(); i++) {
            g.draw(lineContainer.get(i));
        }
        for (int i = 0; i < circContainer.size(); i++) {
            g.draw(circContainer.get(i));
        }
    }

    private void DrawLineHor(double x0, double y0) {
        for (int l = 0; l < 10; l++) {
            double x1 = (x0 + Math.cos(Math.toRadians(0)) * (100 * dH));
            double y1 = (y0 + Math.sin(Math.toRadians(0)) * (100 * dH));
            lineBuffer = new Line2D.Double(x0, y0, x1, y1);
            lineContainer.add(lineBuffer);

            x0 = x1;
            y0 = y1;
//            System.out.println(x0 + " - " + y0);
        }
    }

    private void DrawLineVert(double x0, double y0, double alfa) {
        if (x0 != this.x0 && y0 != this.y0) {

//            System.out.println("ka = " + ka);
            int zona = 0;
            if (z1 < 0) {
                zona = z3;
                System.out.println("zona " + zona);
            } else {
                zona = z1;
                System.out.println("zona " + zona);
            }
            for (int i = zona; i > 0; i--) {
//                System.out.println("i====>>> " + i);
//                for (int qq = 0; qq < i; qq++) {
                double x1 = (x0 + Math.cos(Math.toRadians(180 - alfa)) * (100 * dH));
                double y1 = (y0 + Math.sin(Math.toRadians(180 - alfa)) * (100 * dH));

                lineBuffer = new Line2D.Double(x0, y0, x1, y1);
                lineContainer.add(lineBuffer);

                x0 = x1;
                y0 = y1;

                circBuffer = new Ellipse2D.Double((x0 - 3), (y0 - 3), 6, 6);
                circContainer.add(circBuffer);
                System.out.println("z1 " + z1);

//                }
            }

        } else if (x0 == this.x0 && y0 == this.y0) {
            for (int qq = 0; qq < 10; qq++) {
                double x1 = (x0 + Math.cos(Math.toRadians(180 - alfa)) * (100 * dH));
                double y1 = (y0 + Math.sin(Math.toRadians(180 - alfa)) * (100 * dH));

                lineBuffer = new Line2D.Double(x0, y0, x1, y1);
                lineContainer.add(lineBuffer);

                x0 = x1;
                y0 = y1;

                circBuffer = new Ellipse2D.Double((x0 - 3), (y0 - 3), 6, 6);
                circContainer.add(circBuffer);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextB;
    private javax.swing.JTextField jTextH;
    private javax.swing.JTextField jTexth_bl;
    private javax.swing.JTextField jTextl_sh;
    private javax.swing.JTextField jTextm;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
